version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6
    working_directory: ~/build
    steps:
      - checkout
      - deploy:
          command: |
            cd js
            npm install
            npm run build
            echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login
            npm publish
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global
